org.quartz.scheduler.instanceName=Job_Crontab_Quartz_Scheduler
org.quartz.scheduler.instanceId=AUTO
org.quartz.scheduler.batchTriggerAcquisitionMaxCount=50
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=50
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval=20000
org.quartz.jobStore.useProperties=true
org.quartz.jobStore.selectWithLockSQL=SELECT * FROM {0}LOCKS WHERE LOCK_NAME \= ? FOR UPDATE
org.quartz.jobStore.dataSource=myDS
org.quartz.dataSource.myDS.driver=com.mysql.cj.jdbc.Driver
org.quartz.dataSource.myDS.URL=jdbc:mysql://__BK_JOB_CRONTAB_MYSQL_HOST__:__BK_JOB_CRONTAB_MYSQL_PORT__/job_crontab?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
org.quartz.dataSource.myDS.user=__BK_JOB_CRONTAB_MYSQL_USERNAME__
org.quartz.dataSource.myDS.password=__BK_JOB_CRONTAB_MYSQL_PASSWORD__
org.quartz.dataSource.myDS.maxConnections=30
org.quartz.dataSource.myDS.provider=hikaricp
org.quartz.dataSource.myDS.maximumPoolSize=10
org.quartz.dataSource.myDS.connectionTestQuery=SELECT 1
org.quartz.dataSource.myDS.validationTimeout=5000
org.quartz.dataSource.myDS.idleTimeout=0
org.quartz.scheduler.skipUpdateCheck=true
org.quartz.plugin.triggHistory.class=org.quartz.plugins.history.LoggingJobHistoryPlugin
org.quartz.plugin.shutdownhook.class=org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownhook.cleanShutdown=true
